In [220]:
import numpy as np
import pandas as pd

In [221]:
trainD=pd.read_csv('newsgroups_train.csv')

In [222]:
trainD.shape

(1657, 3)

In [223]:
trainD.head()

text  target       category
0  From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2  From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3  From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4  From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space

In [224]:
from sklearn.feature_extraction.text import CountVectorizer

## converting text into numeric array

In [225]:
count_word=CountVectorizer(max_features=1212)
vectors=count_word.fit_transform(trainD.text)
vectors=vectors.toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [226]:
unique_features = count_word.get_feature_names_out()

# Print all unique features
print(unique_features)

['00' '000' '01' ... 'zip' 'zoo' 'zoology']


In [227]:
X=vectors
y=trainD.target

In [228]:
y.shape

(1657,)

In [229]:
X.shape

(1657, 1212)

In [230]:
y

0       2
1       1
2       0
3       1
4       2
       ..
1652    1
1653    1
1654    2
1655    2
1656    2
Name: target, Length: 1657, dtype: int64

In [231]:
trainD.category

0           sci.space
1       comp.graphics
2         alt.atheism
3       comp.graphics
4           sci.space
            ...      
1652    comp.graphics
1653    comp.graphics
1654        sci.space
1655        sci.space
1656        sci.space
Name: category, Length: 1657, dtype: object

In [232]:
print(trainD.text[1212])

From: cobb@alexia.lis.uiuc.edu (Mike Cobb)
Subject: Re: After 2000 years, can we say that Christian Morality is
Organization: University of Illinois at Urbana
Lines: 47

In <lsran6INN14a@exodus.Eng.Sun.COM> emarsh@hernes-sun.Eng.Sun.COM (Eric 
Marsh) writes:

>In article <C5HqxJ.JDG@ux1.cso.uiuc.edu> lis450bw@ux1.cso.uiuc.edu (lis450 
Student) writes:
>>Hmmmm.  Define objective morality.  Well, depends upon who you talk to.
>>Some say it means you can't have your hair over your ears, and others say
>>it means Stryper is acceptable.  _I_ would say that general principles
>>of objective morality would be listed in one or two places.

>>Ten Commandments

>>Sayings of Jesus

>>the first depends on whether you trust the Bible, 

>>the second depends on both whether you think Jesus is God, and whether
>>  you think we have accurate copies of the NT.

>Gong!

>Take a moment and look at what you just wrote. First you defined
>an "objective" morality and then you qualified this "objective" mora

In [233]:
trainD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1657 entries, 0 to 1656
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   text      1657 non-null   object
 1   target    1657 non-null   int64 
 2   category  1657 non-null   object
dtypes: int64(1), object(2)
memory usage: 39.0+ KB


In [234]:
trainD.describe()

target
count  1657.000000
mean      1.068196
std       0.802056
min       0.000000
25%       0.000000
50%       1.000000
75%       2.000000
max       2.000000

In [235]:
print(trainD[trainD['category'].isin(['alt.atheism','sci.space','comp.graphics'])])

                                                   text  target       category
0     From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1     From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2     From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3     From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4     From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space
...                                                 ...     ...            ...
1652  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
1653  From: renes@ecpdsharmony.cern.ch (Rene S. Dutc...       1  comp.graphics
1654  From: xrcjd@resolve.gsfc.nasa.gov (Charles J. ...       2      sci.space
1655  From: dietz@cs.rochester.edu (Paul Dietz)\nSub...       2      sci.space
1656  From: jhwitten@cs.ruu.nl (Jurriaan Wittenberg)...       2      sci.space

[1657 rows x 3 columns]


## Preparing a Bernoulli Model for the prediction

In [236]:
from sklearn.naive_bayes import BernoulliNB
BNB=BernoulliNB()
BNB.fit(X,y)

BernoulliNB()

In [237]:
testD=pd.read_csv('newsgroups_test.csv')

In [238]:
testD.shape

(1102, 3)

In [239]:
testD.head()

text  target       category
0  From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1  From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2  From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3  From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4  From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics

In [240]:
test_vect=count_word.fit_transform(testD.text)
test_vect=test_vect.toarray()

In [241]:
test_vect

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [242]:
print(test_vect)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [243]:
test_X=test_vect
test_y=testD.target

In [244]:
y_pred=BNB.predict(test_X)

In [245]:
import sklearn.metrics as metrics

print(f'accuracy of Bernoulli model is {metrics.accuracy_score(y_pred,test_y)}')

accuracy of Bernoulli model is 0.5036297640653358


In [246]:
print(metrics.confusion_matrix(y_pred,test_y))

[[ 84  12  32]
 [ 97 257 148]
 [138 120 214]]


In [247]:
print(f' F1 score is {metrics.f1_score(y_pred,test_y,average='macro')}')

 F1 score is 0.4823150547774377


## Converting Text into numeric array using TFidf(Term frequency-Inverse Document frequency)

In [248]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [249]:
tfi=TfidfVectorizer(max_features=1212)
new_train=tfi.fit_transform(trainD.text)

In [250]:
print(tfi.get_feature_names_out())

['00' '000' '01' ... 'zip' 'zoo' 'zoology']


In [251]:
new_train=new_train.toarray()
new_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [252]:
new_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [253]:
new_X=new_train

In [254]:
new_X.shape

(1657, 1212)

# Preparing Multinomial Model

In [255]:
MNB=MultinomialNB()
MNB.fit(new_X,y)

MultinomialNB()

In [256]:
new_test=tfi.fit_transform(testD.text)

In [257]:
new_test=new_test.toarray()
new_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.13598886, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [258]:
new_test.shape

(1102, 1212)

In [259]:
My_pred=MNB.predict(new_test)

In [260]:
print(f'accuracy of the multinomial model is {metrics.accuracy_score(My_pred,test_y)}')

accuracy of the multinomial model is 0.46823956442831216


In [261]:
print(f'F1 score of the multinomial model is {metrics.f1_score(My_pred,test_y,average='macro')}')

F1 score of the multinomial model is 0.46764808715362066


In [262]:
#stop words are less significant words in a language like is an the a 

In [263]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
print(len(ENGLISH_STOP_WORDS))  # Number of stop words
print(list(ENGLISH_STOP_WORDS)[:10])  # Print first 10 stop words


318
['myself', 'your', 'further', 'are', 'why', 'this', 'everyone', 'do', 'well', 'none']


## removing stop words and training the model

In [264]:
tfi=TfidfVectorizer(max_features=1212,stop_words='english')
new_train=tfi.fit_transform(trainD.text)

In [265]:
print(f'accuracy of the multinomial model is {metrics.accuracy_score(My_pred,test_y)}')

accuracy of the multinomial model is 0.46823956442831216
